name: Tests

on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: macos-10.15
    strategy:
      matrix:
        versions:
          - xcode: "11.7"
            ios: "13.7"
          - xcode: "12"
            ios: "14.0"
    steps:
      - uses: actions/checkout@v2
      - name: Install helpers
        run: |
          brew install xcodegen
          gem install xcpretty
      - name: Change Xcode version
        run: sudo xcode-select -s "/Applications/Xcode_${{matrix.versions.xcode}}.app"
      - name: Run tests
        run: |
          set -o pipefail
          xcodegen
          xcodebuild -project Test.xcodeproj -scheme TestApp -sdk iphonesimulator${{matrix.versions.ios}} -destination "platform=iOS Simulator,OS=${{matrix.versions.ios}},name=iPhone 11" test | xcpretty
